### PR TITLE
Laghos, Remhos Bugfix

### LINKED ISSUE #718: Remhos: mfem include
The remhos benchmark has the following include:
`#include "fem/qinterp/det.cpp"`
However, the mfem cmake build does not specify`fem/qinterp/det.cpp` in its list of include headers
This causes the remhos build to fail with the error:
`remhos.cpp:42:10: fatal error: 'fem/qinterp/det.cpp' file not found`

### LINKED ISSUE #757: Default laghos+rocm Fails llnl-elcapitan for rocm>=6
**Describe the bug**

`rocm=5.7.1` - `hipsparse.h` is located `/opt/rocm-5.7.1/include/` (working)
`rocm=6.2.4` (default) - `hipsparse.h` located in `/opt/rocm-6.2.4/include/hipsparse/` causing `mfem` build to fail

```
$ hipcc ... -I/opt/rocm-6.2.4/include

>> 160    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     161       26 | #include <hipsparse.h>
```

**To Reproduce**
1. On benchpark develop
2. `benchpark experiment init --dest laghos laghos+rocm`
3. `benchpark system init --dest tioga llnl-elcapitan cluster=tioga`
4. `benchpark setup laghos tioga wkp`
5. Run ramble setup results in above error

**Discuss**
How to have spack recursively search `/opt/rocm-6.2.4/include/`

### PR DESCRIPTION
**Pull request by rfhaque**
This PR fixes several issues with laghos and remhos builds.

- [x] Update laghos/remhos package.py to use the latest mfem and hypre versions. 
- [x] Fixes the mfem build issue for rocm >= 6 #757
- [x] Closes issues #718, #757, #715
- [x] Subsumes: #719
- [x] Waiting on merge: https://github.com/wdhawkins/Laghos/pull/1
- [x] After https://github.com/wdhawkins/Laghos/pull/1, what needs to be done?  Before merging this PR, the laghos source repo needs to be merged and the URL in laghos package.py should be reverted to the original one
- [x] If modifying the source code of a benchmark: create, self-assign, and link here a follow up issue with a link to the PR in the benchmark repo.
- [x] If package.py upstreamed to Spack is insufficient, add/modify `repo/benchmark_name/package.py` plus: create, self-assign, and link here a follow up issue with a link to the PR in the Spack repo.

Leaving to address in future PRs, documenting in Issues #851 and #852.
- [ ] This PR also uses the latest mfem spack package.py. Once benchpark is updated to the latest spack commit (#762), mfem should use the upstreamed spack version - verify, remove from repo.  
- [ ] Waiting on merge: https://github.com/CEED/Remhos/pull/53. Remhos also tries to include a .cpp file from mfem, that is not installed as a header by the mfem build system (https://github.com/LLNL/benchpark/issues/718). 
- [ ] After https://github.com/CEED/Remhos/pull/53 merge, remove the hack in this PR (explicit copy of the missing include to the intended location). 
- [ ] Waiting on merge: https://github.com/mfem/mfem/pull/4866. 
- [ ] After https://github.com/mfem/mfem/pull/4866 merge, what needs to be done?

Update:
06/24/2025: This PR now uses c++17 standard for the mfem build. It has been tested on tioga/tuolumne, lassen, matrix and dane for both laghos and remhos with the following commit versions:
```
Test date: 06/24/025
benchpark: 01dd9611ee1317a5f9a646236c97946d5a2beb30
ramble: 6b4ecac  # develop on 5/06/2025 (newer than 0.6.0 release)
spack: 7e4b8aa  # develop on 2/22/2025 (pre-breaking changes on 1.0)
```
The test results are as follows:
**Laghos:**
_tioga/tuolumne:_
```
bin/benchpark system init --dest=tuolumne-6.2.4 llnl-elcapitan cluster=elcapitan rocm=6.2.4 +gtl compiler=cce lapack=intel-oneapi-mkl blas=intel-oneapi-mkl
bin/benchpark experiment init --dest laghos-rocm laghos +rocm~cuda caliper=mpi
```
builds: OK
runs: OK

_lassen:_
```
bin/benchpark system init --dest=lassen llnl-sierra cuda=11.8.0 compiler=clang-ibm
bin/benchpark experiment init --dest laghos-cuda laghos +cuda~rocm caliper=cuda,mpi
```
builds: OK
runs: OK

_dane:_
```
bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi (does not work)
bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi2023 (works)
bin/benchpark experiment init --dest laghos-mpionly laghos ~cuda~rocm caliper=mpi
```
builds: Does not build with intel 2022.1.0
hypre gives the following error:
```
pcg.c:604:29: error: invalid suffix 'D' on floating constant
The D suffix is used in Fortran, not C/C++.
```
This is a bug in the Intel OneAPI 2022.1.0 compiler headers.
the code builds OK with oneapi 2023.2.1
runs: OK

_matrix:_
```
bin/benchpark system init --dest=matrix llnl-matrix compiler=gcc cuda=12.2.2
bin/benchpark experiment init --dest laghos-cuda laghos +cuda~rocm caliper=cuda,mpi
```
builds: OK
runs: Fails with the following runtime CUDA error:
```
CUDA ERROR (code = 716, misaligned address) at memory.c:737
CUDA error: (cudaGetLastError()) failed with error:
 --> misaligned address
 ... in function: void mfem::CuWrap1D(int, DBODY&&) [with int BLCK = 256; DBODY = __nv_hdl_wrapper_t<false, false, false, __nv_dl_tag<Vector& (Vector::*)(double), &Vector::operator=, 1>, void(int), double*, double>&]
 ... in file: linalg/../general/forall.hpp:517
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
The same code works for cuda_arch=70 on lassen. **mfem may need to fix this error for cuda_arch=90**

**Remhos:**
_tioga/tuolumne:_
```
bin/benchpark system init --dest=tioga-6.2.4 llnl-elcapitan cluster=tioga rocm=6.2.4 +gtl compiler=cce lapack=intel-oneapi-mkl blas=intel-oneapi-mkl
bin/benchpark experiment init --dest remhos-rocm remhos +rocm~cuda caliper=mpi
```
builds: OK
runs: OK

_lassen:_
```
bin/benchpark system init --dest=lassen llnl-sierra cuda=11.8.0 compiler=clang-ibm
bin/benchpark experiment init --dest remhos-cuda remhos +cuda~rocm caliper=cuda,mpi
```
builds: OK
runs: OK

dane:
```
bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi (does not work)
bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi2023 (works)
bin/benchpark experiment init --dest remhos-mpionly remhos ~cuda~rocm caliper=mpi
```
builds: Does not build with intel 2022.1.0
hypre gives the following error:
```
pcg.c:604:29: error: invalid suffix 'D' on floating constant
The D suffix is used in Fortran, not C/C++.
```
This is a bug in the Intel OneAPI 2022.1.0 compiler headers.
the code builds OK with oneapi 2023.2.1
runs: OK

_matrix:_
```
bin/benchpark system init --dest=matrix llnl-matrix compiler=gcc cuda=12.2.2
bin/benchpark experiment init --dest remhos-cuda remhos +cuda~rocm caliper=cuda,mpi
```
builds: OK
runs: OK

### CODE REVIEW

File: repo/mfem/package.py [hunk 1]
```diff
@@ -4,51 +4,1179 @@
...
+        "3.4.0",
+        sha256="4e73e4fe0482636de3c5dc983cd395839a83cb16f6f509bd88b053e8b3858e05",
+        url="https://bit.ly/mfem-3-4",
+        extension="tar.gz",
+    )
+
+    version(
+        "3.3.2",
+        sha256="b70fa3c5080b9ec514fc05f4a04ff74322b99ac4ecd6d99c229f0ed5188fc0ce",
+        url="https://goo.gl/Kd7Jk8",
```
Comment (michaelmckinsey1) [inline repo/mfem/package.py]: I get these are from upstream, but these `goo.gl` links will no longer work by August 25th https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/

**Comment by michaelmckinsey1** [comment]
@rfhaque I tested this for `laghos` mpi-only and `remhos` mpi-only, which this branch does work in its current state. But after merging develop with #762 I get

```
==> Error: cannot load package 'laghos' from the 'benchpark' repository: the '^' sigil cannot be used in 'depends_on' directives. Please reformulate the directive below as multiple directives:

	depends_on("mfem ^hipblas", when="+rocm")
```

when building remhos. I don't know why it says `laghos`, but `remhos has the same `depends_on("mfem ^hipblas", when="+rocm")`. I assume this is because the new spack. I thought the equivalent should be:

```
    depends_on("mfem", when="+rocm")
    depends_on("hipblas", when="+rocm")
```
but this does not work.

File: repo/mfem/package.py (hunk 1 above)
Comment (rfhaque) [reply repo/mfem/package.py]: This will go away once we move to the upstreamed spack package.py

File: repo/mfem/package.py [hunk 2]
```diff
@@ -4,51 +4,668 @@
...
+            if "^rocthrust" in spec and not spec["hip"].external:
+                # petsc+rocm needs the rocthrust header path
+                hip_headers += spec["rocthrust"].headers
+            if "^rocprim" in spec and not spec["hip"].external:
+                # rocthrust [via petsc+rocm] has a dependency on rocprim
+                hip_headers += spec["rocprim"].headers
+            if "^hipblas" in spec:
+                hipblas = spec["hipblas"]
+                hip_headers += hipblas.headers
+                hip_libs += hipblas.libs
```
Comment (rfhaque) [inline repo/mfem/package.py:493]: @pearce8 @scheibelp @michaelmckinsey1 The latest spack update (7e4b8aa) in benchpark still does not handle the hipblas case correctly in its upstreamed mfem package.py. Once the correct spack version is used, we can remove this function

Comment (pearce8) [reply repo/mfem/package.py:493]: @rfhaque are you saying you need a newer mfem package than feb 22?

Comment (rfhaque) [reply repo/mfem/package.py:493]: > @rfhaque are you saying you need a newer mfem package than feb 22?

Yes

Comment (pearce8) [reply repo/mfem/package.py:493]: @rfhaque then we need to have a copy of the new package in our repo.  We will not be able to update Spack for awhile.

Comment (rfhaque) [reply repo/mfem/package.py:493]: > @rfhaque then we need to have a copy of the new package in our repo. We will not be able to update Spack for awhile.

@pearce8 Yes. These changes are in a later spack commit than what benchpark has pinned.

**Comment by pearce8** [comment]
@michaelmckinsey1 @rfhaque: So I see 2 laghos tests on Dane in CI.  The one with +openmp fails, the one without openmp passes.  Laghos does not have an openmp version - what needs to be fixed here?

**Comment by rfhaque** [comment]
> @michaelmckinsey1 @rfhaque: So I see 2 laghos tests on Dane in CI. The one with +openmp fails, the one without openmp passes. Laghos does not have an openmp version - what needs to be fixed here?

@pearce8 We need to remove `+openmp` from the spec. Since laghos does not support openmp, that spec is invalid

**Comment by michaelmckinsey1** [comment]
@pearce8 @rfhaque This was a refactor mistake made in #834. It is fixed now with [9d12d6c](https://github.com/LLNL/benchpark/pull/770/commits/9d12d6cf0476ffc98ae2b56cb3815042ba85f488)

**Review by pearce8 — APPROVED** [review]
