### ISSUE TITLE
hypre build fails for intel oneapi compiler v2022.1.0

### ISSUE THREAD

**Issue by rfhaque** [LLNL/benchpark#856]
**Describe the bug**
hypre fails to build with the intel oneapi compiler 2022.1.0 on dane. We get the following error
```
pcg.c:604:29: error: invalid suffix 'D' on floating constant
The D suffix is used in Fortran, not C/C++.
```
This seems to be a bug in the Intel OneAPI 2022.1.0 compiler headers.
The code builds correctly with oneapi v2023.2.1

**To Reproduce**
1. `bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi` (default version 2022.1.0)
2. `bin/benchpark experiment init --dest laghos laghos ~cuda~rocm caliper=mpi`
3. `bin/benchpark setup laghos dane <workspace>`
4. `. <workspace>/setup.sh`
5. `ramble --disable-progress-bar --workspace-dir <workspace>/laghos/dane/workspace workspace setup`
6. `ramble --disable-progress-bar --workspace-dir <workspace>/laghos/dane/workspace on`

**Supercomputer (please complete the following information):**
 - system: dane
 - system parameters: compiler=oneapi 
 - experiment: laghos, remhos, amg2023
 - experiment parameters: default

**Additional context**
The code builds correctly with oneapi v2023.2.1
Using the system config `bin/benchpark system init --dest=dane llnl-cluster cluster=dane compiler=oneapi2023` works

**Comment by rfhaque** [comment]
Resolved. Moved the default oneapi compiler to v2023.2.1
